# Generated by Django 5.0.2 on 2024-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="chosen_attribute_values",
            field=models.ManyToManyField(
                blank=True, related_name="attributes", to="users.attributevalue"
            ),
        ),
    ]
