# Generated by Django 5.0.2 on 2024-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empiuser",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
