services:
  api:
    environment:
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      WEB_URL: "http://localhost:3000"
      FROM_EMAIL: "noreply@example.com"
      REPLY_TO_EMAILS: "admin@example.com"
      SENTRY_SDK_DSN: ""
      DJANGO_SECRET_KEY: ""
  web:
    environment:
      COOKIE_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # must be exactly 32 characters long
      ORIGIN: "http://localhost:3000"
      EXT_SERVER_URL: "http://localhost:8000"