version: '3.4'
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      target: api
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: "localhost,api,127.0.0.1"
      DEBUG: "1"
    depends_on:
      - db
  web:
    build:
      context: .
      target: web
      args:
        ORIGIN: "http://localhost:3000"
    ports:
      - "3000:3000"
    environment:
      INT_SERVER_UR: "http://api:8000/"
      EXT_SERVER_URL: "http://127.0.0.1:8000/"
    depends_on:
      - api

volumes:
  postgres_data: