services:
  api:
    environment:
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      WEB_URL: "http://localhost:3000"
      FROM_EMAIL: "noreply@example.com"
      REPLY_TO_EMAILS: "admin@example.com"
  web:
    build:
      args:
        ORIGIN: "http://localhost:3000"
    environment:
      EXT_SERVER_URL: "http://127.0.0.1:8000/"
      COOKIE_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # must be exactly 32 characters long