[tool.poetry]
name = "empi"
version = "0.1.0"
description = "Backend for the Empirical research CMS"
authors = ["David Krchňavý <krchnavy11@uniba.sk>"]
readme = "README.md"

[tool.poetry.urls]
"Homepage" = "https://gitlab.matfyz.sk/znamafirma/empi"
"Bug Tracker" = "https://gitlab.matfyz.sk/znamafirma/empi/-/issues"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.3"
django-cors-headers = "^4.3.1"
djangorestframework = "^3.14.0"
pycryptodome = "^3.20.0"
python-magic = "^0.4.27"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
