[tool.poetry]
name = "empi"
version = "2024.10.29"
description = "Backend for the Empirical research CMS"
authors = ["David Krchňavý <krchnavy11@uniba.sk>"]
readme = "README.md"

[tool.poetry.urls]
"Homepage" = "https://gitlab.matfyz.sk/znamafirma/empi"
"Bug Tracker" = "https://gitlab.matfyz.sk/znamafirma/empi/-/issues"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.1"
django-cors-headers = "^4.3.1"
djangorestframework = "^3.15.1"
pycryptodome = "^3.21.0"
python-magic = "^0.4.27"
django-rest-knox = "^5.0.1"
psycopg = { extras = ["binary"], version = "^3.2.3" }
gunicorn = "^23.0.0"
nanoid = "^2.0.0"
html2text = "^2024.2.26"
drf-spectacular = "^0.27.2"
sentry-sdk = { extras = ["django"], version = "^2.15.0" }
markdown = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
