# Generated by Django 5.0.4 on 2024-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_sent",
            field=models.BooleanField(default=False, editable=False, verbose_name="odoslaný"),
        ),
    ]
