# Generated by Django 5.0.5 on 2024-05-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_remove_email_body_email_context_email_template_name"),
        ("research", "0016_remove_research_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="research",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="research.research",
            ),
        ),
    ]
