# Generated by Django 5.0.6 on 2024-05-30 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_email_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_when',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dátum a čas odoslania'),
            preserve_default=False,
        ),
    ]
