# Generated by Django 5.1.6 on 2025-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('STR', 'String'), ('INT', 'Integer')], default='STR', max_length=3)),
            ],
        ),
    ]
