# Generated by Django 5.1.6 on 2025-02-14 18:46

from django.db import migrations


def add_default_settings(apps, schema_editor):
    Settings = apps.get_model("empi_settings", "Settings")
    acad_year_setting = Settings(name="CURRENT_ACAD_YEAR", value="2024/2025")
    acad_year_setting.save()

    semester_setting = Settings(name="CURRENT_SEMESTER", value="Z")
    semester_setting.save()


class Migration(migrations.Migration):
    dependencies = [
        ('empi_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_settings)
    ]
