# Generated by Django 5.0.6 on 2024-08-17 09:41

import django.db.models.deletion
import empi_server.fields
import research.fields
import research.utils.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("when", models.DateTimeField(verbose_name="kedy")),
                ("capacity", models.IntegerField(verbose_name="kapacita")),
                ("comment", models.TextField(blank=True)),
                ("location", models.TextField(null=True)),
                ("info_url", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BackupKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nonce", models.BinaryField(max_length=16)),
                ("tag", models.BinaryField(max_length=16)),
                ("backup_key", models.BinaryField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_keys", research.fields.SeparatedBinaryField()),
                ("nonce", models.BinaryField()),
                ("tag", models.BinaryField()),
                ("ciphertext", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="ResetKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valid_until", models.DateTimeField()),
                ("backup_key", models.BinaryField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedSessionKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.BinaryField(max_length=1024)),
                ("backup_key", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="research.backupkey")),
            ],
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nanoid",
                    models.CharField(
                        default=research.utils.misc.generate_nanoid, editable=False, max_length=20, unique=True
                    ),
                ),
                ("is_confirmed", models.BooleanField(blank=True, default=False)),
                (
                    "appointment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="research.appointment"),
                ),
                (
                    "encrypted_token",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="research.encryptedtoken"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nanoid",
                    models.CharField(
                        default=research.utils.misc.generate_nanoid, editable=False, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="meno")),
                ("info_url", models.URLField()),
                ("points", models.PositiveIntegerField(blank=True, null=True, verbose_name="body")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_protected", models.BooleanField(default=False, editable=False)),
                ("is_published", models.BooleanField(default=False)),
                ("email_recipients", empi_server.fields.SeparatedValuesField(verbose_name="príjemcovia")),
                ("pubkey", models.TextField(max_length=1024)),
                ("privkey", models.BinaryField(max_length=4096)),
                (
                    "backup_privkey",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="research.backupkey"),
                ),
            ],
        ),
    ]
