# Generated by Django 5.0.3 on 2024-03-11 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="research",
            name="protected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="research",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0019483c-81fd-4e17-8761-6fbf43b66655"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
