# Generated by Django 5.0.4 on 2024-04-22 19:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="research",
            old_name="protected",
            new_name="is_protected",
        ),
        migrations.AddField(
            model_name="participation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="participation",
            name="encrypted_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="research.encryptedtoken",
            ),
        ),
    ]
