# Generated by Django 5.1 on 2024-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_alter_encryptedsessionkey_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="pubkey",
            field=models.BinaryField(max_length=1024),
        ),
    ]
