# Generated by Django 5.1 on 2024-08-28 14:46

import research.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_alter_research_pubkey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participation",
            name="encrypted_token",
        ),
        migrations.AddField(
            model_name="participation",
            name="encrypted_tokens",
            field=research.fields.SeparatedBinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="EncryptedToken",
        ),
    ]
