# Generated by Django 5.0.4 on 2024-04-22 19:34

from django.db import migrations, models

import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_auto_20240422_2134"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        )
    ]
