# Generated by Django 5.1 on 2024-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_remove_participation_encrypted_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
