# Generated by Django 5.0.4 on 2024-04-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_research_email_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="is_protected",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="research",
            name="is_published",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
