# Generated by Django 5.1.1 on 2024-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_research_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="when",
            field=models.DateTimeField(blank=True, null=True, verbose_name="kedy"),
        ),
    ]
