# Generated by Django 5.1.1 on 2024-10-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0007_alter_appointment_when"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="info_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
