# Generated by Django 5.0.4 on 2024-04-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0007_alter_research_is_protected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
