# Generated by Django 5.1.3 on 2024-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_alter_research_info_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="info_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
