# Generated by Django 5.0.5 on 2024-05-08 07:52

import research.utils.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_alter_research_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="nanoid",
            field=models.CharField(
                default=research.utils.misc.generate_nanoid,
                editable=False,
                max_length=20,
                null=True,
            ),
        ),
    ]
