# Generated by Django 5.1.3 on 2024-11-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0009_alter_research_info_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="info_url",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
