# Generated by Django 5.0.5 on 2024-05-08 07:53

from django.db import migrations

import research.utils.misc


def really_generate(apps, schema_editor):
    Participation = apps.get_model("research", "Participation")
    for row in Participation.objects.all():
        row.nanoid = research.utils.misc.generate_nanoid()
        row.save(update_fields=["nanoid"])


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0009_participation_nanoid"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(really_generate, reverse_code=migrations.RunPython.noop),
    ]
