# Generated by Django 5.1.6 on 2025-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_alter_appointment_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='academic_year',
            field=models.CharField(default='2024/2025', editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='participation',
            name='semester',
            field=models.CharField(choices=[('Z', 'Zimný'), ('L', 'Letný')], default='Z', editable=False, max_length=1),
        ),
    ]
