# Generated by Django 5.1.4 on 2024-12-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0010_alter_appointment_info_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="research",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="research.research",
            ),
        ),
    ]
