# Generated by Django 5.1.8 on 2025-06-19 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_participation_academic_year_participation_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
