# Generated by Django 5.0.5 on 2024-05-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0011_auto_20240508_0953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participation",
            name="uuid",
        ),
    ]
