# Generated by Django 5.1.4 on 2024-12-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0011_participation_research"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="research.appointment",
            ),
        ),
    ]
