# Generated by Django 5.0.5 on 2024-05-08 17:28

from django.db import migrations

import research.utils.misc


def really_generate(apps, schema_editor):
    Research = apps.get_model("research", "Research")
    for row in Research.objects.all():
        row.nanoid = research.utils.misc.generate_nanoid()
        row.save(update_fields=["nanoid"])


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0013_research_nanoid"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(really_generate, reverse_code=migrations.RunPython.noop),
    ]
