# Generated by Django 5.0.5 on 2024-05-08 17:28

from django.db import migrations, models

import research.utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_auto_20240508_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="nanoid",
            field=models.CharField(
                default=research.utils.misc.generate_nanoid,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
