# Generated by Django 5.0.6 on 2024-05-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0016_remove_research_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participation",
            old_name="has_participated",
            new_name="is_confirmed",
        ),
    ]
