# Generated by Django 5.0.3 on 2024-04-16 08:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="acad_year",
            field=models.CharField(
                default=users.models.generate_acad_year,
                max_length=7,
                verbose_name="akademický rok",
            ),
        ),
    ]
