# Generated by Django 5.0.4 on 2024-04-22 19:33

import django.contrib.auth.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empiuser",
            options={"default_manager_name": "users"},
        ),
        migrations.AlterModelManagers(
            name="empiuser",
            managers=[
                ("users", users.models.EmpiUserManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
