# Generated by Django 5.1.1 on 2024-10-02 14:26
from django.db import migrations, models
from django.utils import timezone


def current_year():
    return timezone.now().year


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_encryptedsessionkey_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="acad_year",
        ),
        migrations.AddField(
            model_name="participant",
            name="semester",
            field=models.CharField(
                choices=[("z", "zimný"), ("l", "letný")],
                default="z",
                max_length=1,
                verbose_name="semester",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="year",
            field=models.IntegerField(default=current_year, verbose_name="rok štúdia"),
        ),
    ]
