# Generated by Django 5.1.1 on 2024-10-03 13:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_participant_acad_year_participant_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="semester",
            field=models.CharField(
                choices=[("z", "zimný"), ("l", "letný")],
                default=users.models.current_semester,
                max_length=1,
                verbose_name="semester",
            ),
        ),
    ]
