# Generated by Django 5.1.6 on 2025-02-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_participant_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='year',
        ),
    ]
