# Generated by Django 5.0.2 on 2024-03-04 11:08

import django.db.models.deletion
import research.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField(verbose_name="kedy")),
                ("capacity", models.IntegerField(verbose_name="kapacita")),
                ("comment", models.TextField(blank=True)),
                ("location", models.TextField(null=True)),
                ("url", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_keys", research.fields.SeparatedBinaryField()),
                ("nonce", models.BinaryField()),
                ("tag", models.BinaryField()),
                ("ciphertext", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="meno"),
                ),
                ("url", models.URLField()),
                ("points", models.PositiveIntegerField(verbose_name="body")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_participated", models.BooleanField(blank=True, default=False)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.appointment",
                    ),
                ),
                (
                    "encrypted_token",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.encryptedtoken",
                    ),
                ),
            ],
        ),
    ]
