# Generated by Django 5.0.2 on 2024-03-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="research",
            old_name="url",
            new_name="info_url",
        ),
    ]
