# Generated by Django 5.0.2 on 2024-02-24 19:35

import emails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="recipients",
            field=emails.fields.SeparatedValuesField(
                default="", verbose_name="príjemcovia"
            ),
            preserve_default=False,
        ),
    ]
